from z3 import *
from aux_z3 import *
s = set()
n = Int("n")
N0 = Int("N0")
s.add(N0 >= 0)
N1 = Int("N1")
s.add(N1 >= 0)
solver = Solver()
solver.set("timeout", 2000)
n1 = Int("n1")
n2 = Int("n2")
i1 = Int("i1")
i2 = Int("i2")
i3 = Function("i3", IntSort(), IntSort())
i4 = Int("i4")
j1 = Int("j1")
j2 = Int("j2")
j3 = Function("j3", IntSort(), IntSort())
j4 = Int("j4")
j5 = Function("j5", IntSort(), IntSort())
j6 = Int("j6")
k1 = Int("k1")
k2 = Int("k2")
k3 = Function("k3", IntSort(), IntSort())
k4 = Int("k4")
tmp3 = Int("tmp3")
tmp1 = Int("tmp1")
tmp4 = Int("tmp4")
tmp2 = Int("tmp2")
tmp0 = Int("tmp0")
s.add(n1 == tmp0)
s.add(i1 == tmp1)
s.add(j1 == tmp2)
s.add(k1 == tmp3)
s.add(n2 == tmp4)
s.add(i2 == 0)
s.add(j2 == 0)
s.add(i3(0) == i2)
s.add(ForAll(n, Implies(n >= 0, i3(n + 1) == If(True, i3(n) + 4, i3(n) + 4))))
########## closed form ##########
s.add(ForAll(n, Implies(n >= 0, i3(n) == If(And(0 <= n, n < 1), 0, 4*n))))
#################################
s.add(i4 == i3(N0))
s.add(j3(0) == j2)
s.add(ForAll(n, Implies(n >= 0, j3(n + 1) == If(True, i3(n) + 6, i3(n) + 6))))
########## closed form ##########
s.add(ForAll(n, Implies(n >= 0, -1*j3(n) == If(And(0 <= n, n < 1), 0, 2*(2*n + 1)*(Heaviside(-n) - 1)))))
#################################
s.add(j4 == j3(N0))
s.add(ForAll(n, Implies(And(0 <= n, n < N0), i3(n) < n2)))
s.add(Not(i3(N0) < n2))
s.add(k2 == i4)
s.add(j5(0) == j4)
s.add(ForAll(n, Implies(n >= 0, j5(n + 1) == If(True, j5(n) - 4, j5(n) - 4))))
########## closed form ##########
s.add(ForAll(n, Implies(n >= 0, j5(n) == j4 - 4*n)))
#################################
s.add(j6 == j5(N1))
s.add(k3(0) == k2)
s.add(ForAll(n, Implies(n >= 0, k3(n + 1) == If(True, k3(n) - 4, k3(n) - 4))))
########## closed form ##########
s.add(ForAll(n, Implies(n >= 0, k3(n) == i4 - 4*n)))
#################################
s.add(k4 == k3(N1))
s.add(ForAll(n, Implies(And(0 <= n, n < N1), Eq(Mod(j5(n), 2), 0))))
s.add(Not(Eq(Mod(j5(N1), 2), 0)))
########## assert ##########
############################
